algoritmo "RepeticaocomFacaEnquanto"


var
      P, U, I, n: Inteiro
inicio
       Escreval ("Primeiro número da sequencia: ")
       Leia (P)
       Escreval ("Ultimo númera da sequencia: ")
       Leia (U)
       Escreval ("Intervalo: ")
       Leia (I)

       Escreva (P)
       Enquanto (n < U) faca
            n <- n + P
            n <- N + I
            Escreva (N)
       FimEnquanto
fimalgoritmo
