algoritmo "ConversorSimples"
// Função :
// Autor :
// Data : 19/10/2022
// Seção de Declarações 
var
       R, D, T: real
inicio
       Escreva ("Quanto dinheiro você tem na carteira? ")
       Leia (R)

       D <- 3.45
       T <- R/D
       
       Escreval ("Considerando o dolar a R$ 3,45, com o valor R$", R," que você possui na carteira, poderia trocar por US$ ", T:2:2)
fimalgoritmo
