algoritmo "VerificadorImparouPar"


var
     N: Inteiro
inicio
     Escreva ("Digite um número: ")
     Leia (N)
     
     Escreval (". . . . . . . . . . . . . . .")
     Escreval ("       P E N S A N D O       ")
     Escreval (". . . . . . . . . . . . . . .")
     
     Se (N% 2=1) entao
        Escreval ("O número", N, " é Ímpar.")
     senao
        Escreval ("O número", N, " é Par.")
     FimSe
fimalgoritmo
